/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.Role;
import models.Student;
import models.UserApplication;
import services.StudentService;
import services.UserApplicationService;
import thread.ViewThread;
import utils.MyFile;

/**
 *
 * @author dinhh
 */
public class StudentManagement extends javax.swing.JFrame {

    UserApplication user = null;
    StudentService service = StudentService.getInstance();
    private List<Student> listFind = new ArrayList<>();

    /**
     * Creates new form StudentManagement
     */
    public StudentManagement() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.start(null);
    }

    public StudentManagement(UserApplication user) {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.start(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDashboard = new javax.swing.JLabel();
        txtStudents = new javax.swing.JLabel();
        txtTopStudents = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        txtMyInfo = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        txtRole = new javax.swing.JLabel();
        txtLogout = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblClock = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTop = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnExportStudents = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblTop2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblTop1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblTop3 = new javax.swing.JLabel();
        pnlStudents = new javax.swing.JPanel();
        lblFullname = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblEn = new javax.swing.JLabel();
        lblTech = new javax.swing.JLabel();
        lblPhysical = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtFullname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblTileStudents = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        cboMinEn = new javax.swing.JComboBox<>();
        cboMaxEn = new javax.swing.JComboBox<>();
        cboMinIT = new javax.swing.JComboBox<>();
        cboMaxIT = new javax.swing.JComboBox<>();
        cboMinPE = new javax.swing.JComboBox<>();
        cboMaxPE = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnExportFind = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        pnldashBoard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDashboard = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblNumberDashboard = new javax.swing.JLabel();
        btnExportDashboard = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sm.gif"))); // NOI18N
        jLabel1.setText("Student Management");

        txtDashboard.setBackground(new java.awt.Color(204, 51, 0));
        txtDashboard.setForeground(new java.awt.Color(51, 51, 51));
        txtDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dashboard.png"))); // NOI18N
        txtDashboard.setText("Dashboard");
        txtDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDashboardMouseEntered(evt);
            }
        });

        txtStudents.setForeground(new java.awt.Color(51, 51, 51));
        txtStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/group.png"))); // NOI18N
        txtStudents.setText("Students");
        txtStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStudentsMouseClicked(evt);
            }
        });

        txtTopStudents.setForeground(new java.awt.Color(51, 51, 51));
        txtTopStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTopStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/popular.png"))); // NOI18N
        txtTopStudents.setText("Top Students");
        txtTopStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTopStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTopStudentsMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.setForeground(new java.awt.Color(204, 204, 255));

        txtMyInfo.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        txtMyInfo.setForeground(new java.awt.Color(51, 51, 51));
        txtMyInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMyInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/discord.gif"))); // NOI18N
        txtMyInfo.setText("My info");
        txtMyInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUsername.setForeground(new java.awt.Color(51, 51, 51));
        txtUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUsername.setText("Name: ");

        txtRole.setForeground(new java.awt.Color(51, 51, 51));
        txtRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRole.setText("Role: ");

        txtLogout.setBackground(new java.awt.Color(102, 102, 255));
        txtLogout.setForeground(new java.awt.Color(51, 51, 51));
        txtLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogout.setText("Logout");
        txtLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(txtRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtMyInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtMyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));

        lblClock.setBackground(new java.awt.Color(255, 255, 255));
        lblClock.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sun.png"))); // NOI18N
        lblClock.setText("CLock");
        lblClock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblClock, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(txtTopStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTopStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        pnlTop.setBackground(new java.awt.Color(204, 204, 255));
        pnlTop.setForeground(new java.awt.Color(204, 204, 255));

        tblTop.setBackground(new java.awt.Color(204, 204, 255));
        tblTop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Top", "Fullname", "English", "IT", "Physical Education", "GPA"
            }
        ));
        tblTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTopMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTop);

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ranking.gif"))); // NOI18N
        jLabel2.setText("Top 10 students");

        btnExportStudents.setBackground(new java.awt.Color(153, 255, 204));
        btnExportStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/folder.png"))); // NOI18N
        btnExportStudents.setText("Export file");
        btnExportStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportStudentsMouseClicked(evt);
            }
        });
        btnExportStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportStudentsActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/top2.png"))); // NOI18N
        jLabel12.setText("Top 2");

        lblTop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTop2.setText("???");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTop2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(36, 36, 36)
                .addComponent(lblTop2)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setForeground(new java.awt.Color(255, 204, 204));

        jLabel15.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/top1.png"))); // NOI18N
        jLabel15.setText("Top 1");

        lblTop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTop1.setText("???");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTop1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(35, 35, 35)
                .addComponent(lblTop1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));

        jLabel16.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/top3.png"))); // NOI18N
        jLabel16.setText("Top 3");

        lblTop3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTop3.setText("???");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(34, 34, 34)
                .addComponent(lblTop3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlTopLayout.createSequentialGroup()
                                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlTopLayout.createSequentialGroup()
                                        .addGap(0, 285, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(215, 215, 215))
                                    .addGroup(pnlTopLayout.createSequentialGroup()
                                        .addGap(258, 258, 258)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(btnExportStudents))))
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExportStudents))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.add(pnlTop, "card4");

        pnlStudents.setBackground(new java.awt.Color(204, 204, 255));

        lblFullname.setText("Fullname:");

        lblEmail.setText("Email:");

        lblId.setText("ID:");

        lblEn.setText("English:");

        lblTech.setText("Technologies:");

        lblPhysical.setText("Physical:");

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKeyReleased(evt);
            }
        });

        txtFullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFullnameKeyReleased(evt);
            }
        });

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        lblTileStudents.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        lblTileStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/student.png"))); // NOI18N
        lblTileStudents.setText("Students");

        btnFind.setBackground(new java.awt.Color(204, 255, 204));
        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/find.png"))); // NOI18N
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        cboMinEn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.0", "0.25", "0.5", "0.75", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "3.25", "3.5", "3.75", "4.0", "4.25", "4.5", "4.75", "5.0", "5.25", "5.5", "5.75", "6.0", "6.25", "6.5", "6.75", "7.0", "7.25", "7.5", "7.75", "8.0", "8.25", "8.5", "8.75", "9.0", "9.25", "9.5", "9.75", "10.0" }));
        cboMinEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMinEnActionPerformed(evt);
            }
        });
        cboMinEn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cboMinEnKeyReleased(evt);
            }
        });

        cboMaxEn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.0", "0.25", "0.5", "0.75", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "3.25", "3.5", "3.75", "4.0", "4.25", "4.5", "4.75", "5.0", "5.25", "5.5", "5.75", "6.0", "6.25", "6.5", "6.75", "7.0", "7.25", "7.5", "7.75", "8.0", "8.25", "8.5", "8.75", "9.0", "9.25", "9.5", "9.75", "10.0" }));
        cboMaxEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaxEnActionPerformed(evt);
            }
        });

        cboMinIT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.0", "0.25", "0.5", "0.75", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "3.25", "3.5", "3.75", "4.0", "4.25", "4.5", "4.75", "5.0", "5.25", "5.5", "5.75", "6.0", "6.25", "6.5", "6.75", "7.0", "7.25", "7.5", "7.75", "8.0", "8.25", "8.5", "8.75", "9.0", "9.25", "9.5", "9.75", "10.0" }));
        cboMinIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMinITActionPerformed(evt);
            }
        });
        cboMinIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cboMinITKeyReleased(evt);
            }
        });

        cboMaxIT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.0", "0.25", "0.5", "0.75", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "3.25", "3.5", "3.75", "4.0", "4.25", "4.5", "4.75", "5.0", "5.25", "5.5", "5.75", "6.0", "6.25", "6.5", "6.75", "7.0", "7.25", "7.5", "7.75", "8.0", "8.25", "8.5", "8.75", "9.0", "9.25", "9.5", "9.75", "10.0" }));
        cboMaxIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaxITActionPerformed(evt);
            }
        });

        cboMinPE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.0", "0.25", "0.5", "0.75", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "3.25", "3.5", "3.75", "4.0", "4.25", "4.5", "4.75", "5.0", "5.25", "5.5", "5.75", "6.0", "6.25", "6.5", "6.75", "7.0", "7.25", "7.5", "7.75", "8.0", "8.25", "8.5", "8.75", "9.0", "9.25", "9.5", "9.75", "10.0" }));
        cboMinPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMinPEActionPerformed(evt);
            }
        });

        cboMaxPE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.0", "0.25", "0.5", "0.75", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "3.25", "3.5", "3.75", "4.0", "4.25", "4.5", "4.75", "5.0", "5.25", "5.5", "5.75", "6.0", "6.25", "6.5", "6.75", "7.0", "7.25", "7.5", "7.75", "8.0", "8.25", "8.5", "8.75", "9.0", "9.25", "9.5", "9.75", "10.0" }));
        cboMaxPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaxPEActionPerformed(evt);
            }
        });

        jLabel3.setText("Min");

        jLabel4.setText("Max");

        jLabel5.setText("Min");

        jLabel6.setText("Max");

        jLabel7.setText("Min");

        jLabel8.setText("Max");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(txtAddress);

        jLabel9.setText("Address:");

        btnReset.setBackground(new java.awt.Color(255, 204, 204));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnExportFind.setBackground(new java.awt.Color(153, 255, 204));
        btnExportFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/folder.png"))); // NOI18N
        btnExportFind.setText("Export file");
        btnExportFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportFindMouseClicked(evt);
            }
        });
        btnExportFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportFindActionPerformed(evt);
            }
        });

        tblStudents.setAutoCreateRowSorter(true);
        tblStudents.setBackground(new java.awt.Color(204, 204, 255));
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Fullname", "Email", "Phone number", "Sex"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblStudents);

        javax.swing.GroupLayout pnlStudentsLayout = new javax.swing.GroupLayout(pnlStudents);
        pnlStudents.setLayout(pnlStudentsLayout);
        pnlStudentsLayout.setHorizontalGroup(
            pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentsLayout.createSequentialGroup()
                .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStudentsLayout.createSequentialGroup()
                        .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlStudentsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExportFind)
                                .addGap(3, 3, 3))
                            .addGroup(pnlStudentsLayout.createSequentialGroup()
                                .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlStudentsLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlStudentsLayout.createSequentialGroup()
                                                .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(lblEmail))
                                                .addGap(14, 14, 14))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlStudentsLayout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(lblFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlStudentsLayout.createSequentialGroup()
                                        .addGap(229, 229, 229)
                                        .addComponent(lblTileStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlStudentsLayout.createSequentialGroup()
                                        .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentsLayout.createSequentialGroup()
                                                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(4, 4, 4)))
                                            .addGroup(pnlStudentsLayout.createSequentialGroup()
                                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentsLayout.createSequentialGroup()
                                                .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblPhysical, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblTech, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(pnlStudentsLayout.createSequentialGroup()
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cboMinPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(pnlStudentsLayout.createSequentialGroup()
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cboMinIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentsLayout.createSequentialGroup()
                                                .addComponent(lblEn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cboMinEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboMaxIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboMaxEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboMaxPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane4))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlStudentsLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStudentsLayout.setVerticalGroup(
            pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTileStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlStudentsLayout.createSequentialGroup()
                        .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEn)
                            .addComponent(cboMinEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMaxEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFullname)
                            .addComponent(lblTech)
                            .addComponent(cboMinIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMaxIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail)
                            .addComponent(lblPhysical)
                            .addComponent(cboMinPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMaxPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFind)
                    .addComponent(btnReset)
                    .addComponent(btnExportFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(pnlStudents, "card3");

        pnldashBoard.setBackground(new java.awt.Color(204, 204, 255));
        pnldashBoard.setForeground(new java.awt.Color(153, 153, 255));

        tblDashboard.setAutoCreateRowSorter(true);
        tblDashboard.setBackground(new java.awt.Color(204, 204, 255));
        tblDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Fullname", "Email", "Phone number", "Sex"
            }
        ));
        tblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDashboardMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDashboard);

        btnAdd.setBackground(new java.awt.Color(0, 153, 102));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bot.gif"))); // NOI18N
        jLabel11.setText("Dashboard");

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-avatar.gif"))); // NOI18N
        jLabel10.setText("Number of students:");

        lblNumberDashboard.setText("99");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumberDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumberDashboard))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btnExportDashboard.setBackground(new java.awt.Color(153, 255, 204));
        btnExportDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/folder.png"))); // NOI18N
        btnExportDashboard.setText("Export file");
        btnExportDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportDashboardMouseClicked(evt);
            }
        });
        btnExportDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnldashBoardLayout = new javax.swing.GroupLayout(pnldashBoard);
        pnldashBoard.setLayout(pnldashBoardLayout);
        pnldashBoardLayout.setHorizontalGroup(
            pnldashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldashBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldashBoardLayout.createSequentialGroup()
                        .addComponent(btnExportDashboard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)))
            .addGroup(pnldashBoardLayout.createSequentialGroup()
                .addGroup(pnldashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldashBoardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnldashBoardLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addGroup(pnldashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnldashBoardLayout.setVerticalGroup(
            pnldashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldashBoardLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnldashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldashBoardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnldashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExportDashboard, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(pnldashBoardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel1.add(pnldashBoard, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddFrame add = new AddFrame(user, this);
    }//GEN-LAST:event_btnAddActionPerformed

    public void updateAllTable() {
        updateTableDashBoard();
        btnFindActionPerformed(null);
        updateTableTop();
    }

    public void start(UserApplication user) {
        this.user = user;
        if (user == null) {
            this.setVisible(false);
            LoginFrame login = new LoginFrame();
            login.start();
            return;
        }
        if (user.getRole().equals(Role.Teacher)) {
            this.btnAdd.setVisible(false);
        }
        this.txtUsername.setText("Name: " + user.getUsername());
        this.txtRole.setText("Role: " + (user.getRole().equals(Role.Manager) ? "Manager" : "Teacher"));
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.txtUsername.requestFocus();
        this.pnldashBoard.setVisible(true);
        this.pnlTop.setVisible(false);
        this.pnlStudents.setVisible(false);
        this.updateTableDashBoard();
        this.resetFormFind();
        new ViewThread(this.lblClock).start();
        this.btnFind.setVisible(false);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                showSuccess("Thank you for using the program hello and see you again");
            }
        });

    }

    private void tblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDashboardMouseClicked
        // TODO add your handling code here:
        JTable table = (JTable) evt.getSource();
        int row = table.rowAtPoint(evt.getPoint());
        String id = table.getValueAt(row, 0).toString();

//        ViewDetail viewDetail = new ViewDetail(user, this, id);
        ArrayList<Student> list = (ArrayList<Student>) service.getStudents();
//        ViewDetail viewDetail = new ViewDetail(user, this, id);
        ViewDetail viewDetail = new ViewDetail(user, this, row, list);
    }//GEN-LAST:event_tblDashboardMouseClicked

    private String showInputFile() {
        JFileChooser fc = new JFileChooser();

        int returnValue = fc.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fc.getSelectedFile();
            return String.valueOf(selectedFile);
        }

        return null;
    }

    public UserApplication getUser() {
        return user;
    }

    private void updateTableDashBoard() {
        DefaultTableModel model = (DefaultTableModel) tblDashboard.getModel();
        model.setRowCount(0);
        List<Student> list = service.getStudents();
        lblNumberDashboard.setText("" + list.size());
        if (!list.isEmpty()) {
            for (Student x : list) {
                model.addRow(new Object[]{x.getId(), x.getFullName(), x.getEmail(), x.getPhoneNumber(), x.getSex() == 1 ? "Nam" : "Nữ"});
            }
        }

    }

    private void updateTableTop() {
        DefaultTableModel model = (DefaultTableModel) tblTop.getModel();
        model.setRowCount(0);
        int i = 0;

        List<Student> list = service.top10Student();
        if (!list.isEmpty()) {
            for (Student x : list) {
                if (i == 0) {
                    lblTop1.setText(x.getFullName());
                } else if (i == 1) {
                    lblTop2.setText(x.getFullName());
                } else if (i == 2) {
                    lblTop3.setText(x.getFullName());
                }
                ++i;
                model.addRow(new Object[]{x.getId(), x.getFullName(), x.getEnglish(), x.getTech(), x.getPhysicalEducation(), (x.getEnglish() + x.getTech() + x.getPhysicalEducation()) / 3});
            }
        }
    }

    private void updateTableStudents(List<Student> list) {
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0);
        this.listFind = list;
        if (!list.isEmpty()) {
            for (Student x : list) {
                model.addRow(new Object[]{x.getId(), x.getFullName(), x.getEmail(), x.getPhoneNumber(), x.getSex() == 1 ? "Nam" : "Nữ"});
            }
        }

    }

    private void btnExportStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportStudentsMouseClicked
        // TODO add your handling code here:
        showInputFile();
    }//GEN-LAST:event_btnExportStudentsMouseClicked

    private void cboMinEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMinEnActionPerformed
        // TODO add your handling code here:
        btnFindActionPerformed(null);

    }//GEN-LAST:event_cboMinEnActionPerformed

    private void cboMaxPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaxPEActionPerformed
        // TODO add your handling code here:
        btnFindActionPerformed(null);

    }//GEN-LAST:event_cboMaxPEActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String name = txtFullname.getText();
        String email = txtEmail.getText();
        String id = txtId.getText();
        String address = txtAddress.getText();

        String minEn = (String) cboMinEn.getSelectedItem();
        String maxEn = (String) cboMaxEn.getSelectedItem();
        String minIT = (String) cboMinIT.getSelectedItem();
        String maxIT = (String) cboMaxIT.getSelectedItem();
        String minPE = (String) cboMinPE.getSelectedItem();
        String maxPE = (String) cboMaxPE.getSelectedItem();

        ArrayList<Student> list = (ArrayList<Student>) service.getStudents();
        List<Student> listFind = this.findByOption(list, id, name, minEn, maxEn, minIT, maxIT, minPE, maxPE, address);
        updateTableStudents(listFind);


    }//GEN-LAST:event_btnFindActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:

        resetFormFind();
        btnFindActionPerformed(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTopMouseClicked
        // TODO add your handling code here:

        JTable table = (JTable) evt.getSource();
        int row = table.rowAtPoint(evt.getPoint());
        String id = table.getValueAt(row, 0).toString();
        List<Student> list = service.top10Student();

//        ViewDetail viewDetail = new ViewDetail(user, this, id);
        ViewDetail viewDetail = new ViewDetail(user, this, row, (ArrayList<Student>) list);

    }//GEN-LAST:event_tblTopMouseClicked

    private void txtLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogoutMouseClicked
        // TODO add your handling code here:
        LoginFrame login = new LoginFrame();
        login.start();
        this.dispose();
    }//GEN-LAST:event_txtLogoutMouseClicked

    private void txtTopStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTopStudentsMouseClicked
        // TODO add your handling code here:
        this.pnldashBoard.setVisible(false);
        this.pnlTop.setVisible(true);
        this.pnlStudents.setVisible(false);
        this.updateTableTop();
    }//GEN-LAST:event_txtTopStudentsMouseClicked

    private void txtStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStudentsMouseClicked
        // TODO add your handling code here:
        this.pnldashBoard.setVisible(false);
        this.pnlTop.setVisible(false);
        this.pnlStudents.setVisible(true);
        this.btnFindActionPerformed(null);
    }//GEN-LAST:event_txtStudentsMouseClicked

    private void txtDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDashboardMouseEntered
        // TODO add your handling code here:
        txtDashboard.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtDashboardMouseEntered

    private void txtDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDashboardMouseClicked
        // TODO add your handling code here:
        this.pnldashBoard.setVisible(true);
        this.pnlTop.setVisible(false);
        this.pnlStudents.setVisible(false);
    }//GEN-LAST:event_txtDashboardMouseClicked

    private void btnExportFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportFindMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportFindMouseClicked

    private void btnExportDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportDashboardMouseClicked

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        // TODO add your handling code here:
        JTable table = (JTable) evt.getSource();
        int row = table.rowAtPoint(evt.getPoint());
        String id = table.getValueAt(row, 0).toString();

//        ViewDetail viewDetail = new ViewDetail(user, this, id);
        ViewDetail viewDetail = new ViewDetail(user, this, row, (ArrayList<Student>) listFind);


    }//GEN-LAST:event_tblStudentsMouseClicked

    private void btnExportStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportStudentsActionPerformed
        // TODO add your handling code here:
        List<Student> list = service.top10Student();
        if (list.isEmpty()) {
            showWarn("The list is empty");

        } else {
            try {
                String path = showInputFile();
                if (path == null) {
                    return;
                }
                MyFile.writeExcel(list, path);
                showSuccess("Save file successfully");
            } catch (Exception ex) {
                showErr("Something went wrong");
                Logger.getLogger(StudentManagement.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnExportStudentsActionPerformed
    public List<Student> findByOption(
            ArrayList<Student> list,
            String id,
            String name,
            String minEn,
            String maxEn,
            String minIT,
            String maxIT,
            String minPE,
            String maxPE,
            String address) {

        return list.stream()
                .filter(a -> ((id.isEmpty() || a.getId().toLowerCase().contains(id.toLowerCase()))
                && (name.isEmpty() || a.getFullName().toLowerCase().contains(name.toLowerCase()))
                && (address.isEmpty() || a.getAddress().toLowerCase().contains(address.toLowerCase()))
                && (minEn.isEmpty() || a.getEnglish() >= Double.parseDouble(minEn))
                && (minIT.isEmpty() || a.getTech() >= Double.parseDouble(minIT))
                && (minPE.isEmpty() || a.getPhysicalEducation() >= Double.parseDouble(minPE))
                && (maxEn.isEmpty() || a.getEnglish() <= Double.parseDouble(maxEn))
                && (maxIT.isEmpty() || a.getEnglish() <= Double.parseDouble(maxIT))
                && (maxPE.isEmpty() || a.getEnglish() <= Double.parseDouble(maxPE))))
                .collect(Collectors.toList());
    }


    private void btnExportFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportFindActionPerformed
        // TODO add your handling code here:
        if (this.listFind.isEmpty()) {
            showWarn("The list is empty");
        } else {
            try {
                String path = showInputFile();
                if (path == null) {
                    return;
                }
                MyFile.writeExcel(listFind, path);
                showSuccess("Save file successfully");
            } catch (Exception ex) {
                showErr("Something went wrong");
                Logger.getLogger(StudentManagement.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnExportFindActionPerformed

    private void showSuccess(String mess) {
        JOptionPane.showMessageDialog(this, mess, "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    private void btnExportDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportDashboardActionPerformed
        // TODO add your handling code here:
        List<Student> list = service.getStudents();
        if (list.isEmpty()) {
            showWarn("The list is empty");

        } else {
            try {
                String path = showInputFile();
                if (path == null) {
                    return;
                }
                MyFile.writeExcel(list, path);
                showSuccess("Save file successfully");
            } catch (Exception ex) {
                showErr("Something went wrong");
                Logger.getLogger(StudentManagement.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnExportDashboardActionPerformed

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKeyPressed

    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyReleased
        // TODO add your handling code here:
        btnFindActionPerformed(null);

    }//GEN-LAST:event_txtIdKeyReleased

    private void txtFullnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullnameKeyReleased
        // TODO add your handling code here:
        btnFindActionPerformed(null);

    }//GEN-LAST:event_txtFullnameKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        btnFindActionPerformed(null);

    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased
        // TODO add your handling code here:
        btnFindActionPerformed(null);

    }//GEN-LAST:event_txtAddressKeyReleased

    private void cboMinEnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMinEnKeyReleased
        // TODO add your handling code here:
        btnFindActionPerformed(null);

    }//GEN-LAST:event_cboMinEnKeyReleased

    private void cboMinITKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMinITKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_cboMinITKeyReleased

    private void cboMinITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMinITActionPerformed
        // TODO add your handling code here:
        btnFindActionPerformed(null);

    }//GEN-LAST:event_cboMinITActionPerformed

    private void cboMinPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMinPEActionPerformed
        // TODO add your handling code here:
        btnFindActionPerformed(null);

    }//GEN-LAST:event_cboMinPEActionPerformed

    private void cboMaxEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaxEnActionPerformed
        // TODO add your handling code here:
        btnFindActionPerformed(null);

    }//GEN-LAST:event_cboMaxEnActionPerformed

    private void cboMaxITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaxITActionPerformed
        // TODO add your handling code here:
        btnFindActionPerformed(null);

    }//GEN-LAST:event_cboMaxITActionPerformed

    private void showErr(String mess) {
        JOptionPane.showMessageDialog(this, mess, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void showWarn(String message) {
        JOptionPane.showMessageDialog(this, message, "Warning", JOptionPane.WARNING_MESSAGE);

    }

    private void resetFormFind() {
        txtFullname.setText("");
        txtEmail.setText("");
        txtId.setText("");
        txtAddress.setText("");

        cboMinEn.setSelectedIndex(0);
        cboMinIT.setSelectedIndex(0);
        cboMinPE.setSelectedIndex(0);

        cboMaxEn.setSelectedIndex(cboMaxEn.getItemCount() - 1);
        cboMaxIT.setSelectedIndex(cboMaxIT.getItemCount() - 1);
        cboMaxPE.setSelectedIndex(cboMaxPE.getItemCount() - 1);
        txtId.requestFocus();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagement();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExportDashboard;
    private javax.swing.JButton btnExportFind;
    private javax.swing.JButton btnExportStudents;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cboMaxEn;
    private javax.swing.JComboBox<String> cboMaxIT;
    private javax.swing.JComboBox<String> cboMaxPE;
    private javax.swing.JComboBox<String> cboMinEn;
    private javax.swing.JComboBox<String> cboMinIT;
    private javax.swing.JComboBox<String> cboMinPE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEn;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNumberDashboard;
    private javax.swing.JLabel lblPhysical;
    private javax.swing.JLabel lblTech;
    private javax.swing.JLabel lblTileStudents;
    private javax.swing.JLabel lblTop1;
    private javax.swing.JLabel lblTop2;
    private javax.swing.JLabel lblTop3;
    private javax.swing.JPanel pnlStudents;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnldashBoard;
    private javax.swing.JTable tblDashboard;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTable tblTop;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtId;
    private javax.swing.JLabel txtLogout;
    private javax.swing.JLabel txtMyInfo;
    private javax.swing.JLabel txtRole;
    private javax.swing.JLabel txtStudents;
    private javax.swing.JLabel txtTopStudents;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
