/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bai2;

import javax.swing.JOptionPane;

/**
 *
 * @author dinhh
 */
public class Caculator extends javax.swing.JFrame {

    private double result = 0;
    private String operator = "";
    private boolean check = false;
    private boolean checkZero = false;

    /**
     * Creates new form ManagementStudent
     */
    public Caculator() {
        initComponents();
        this.txtResult.setText("0");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResult = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMultip = new javax.swing.JButton();
        btnChiaLayDu = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnPatial = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResult.setEditable(false);
        txtResult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtResult.setForeground(new java.awt.Color(51, 51, 255));
        txtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResult.setText("0");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("CASIO");

        jPanel1.setLayout(new java.awt.GridLayout(4, 5));

        btn1.setText("1");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        btn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn1KeyPressed(evt);
            }
        });
        jPanel1.add(btn1);

        btn2.setText("2");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        btn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn2KeyPressed(evt);
            }
        });
        jPanel1.add(btn2);

        btn3.setText("3");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        btn3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn3KeyPressed(evt);
            }
        });
        jPanel1.add(btn3);

        btnDivide.setText("/");
        btnDivide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivideMouseClicked(evt);
            }
        });
        btnDivide.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDivideKeyPressed(evt);
            }
        });
        jPanel1.add(btnDivide);

        btnSqrt.setText("sqrt");
        btnSqrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSqrtMouseClicked(evt);
            }
        });
        btnSqrt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSqrtKeyPressed(evt);
            }
        });
        jPanel1.add(btnSqrt);

        btn4.setText("4");
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        btn4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn4KeyPressed(evt);
            }
        });
        jPanel1.add(btn4);

        btn5.setText("5");
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        btn5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn5KeyPressed(evt);
            }
        });
        jPanel1.add(btn5);

        btn6.setText("6");
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        btn6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn6KeyPressed(evt);
            }
        });
        jPanel1.add(btn6);

        btnMultip.setText("*");
        btnMultip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultipMouseClicked(evt);
            }
        });
        btnMultip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultipActionPerformed(evt);
            }
        });
        btnMultip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMultipKeyPressed(evt);
            }
        });
        jPanel1.add(btnMultip);

        btnChiaLayDu.setText("%");
        btnChiaLayDu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChiaLayDuMouseClicked(evt);
            }
        });
        btnChiaLayDu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaLayDuActionPerformed(evt);
            }
        });
        btnChiaLayDu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnChiaLayDuKeyPressed(evt);
            }
        });
        jPanel1.add(btnChiaLayDu);

        btn7.setText("7");
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        btn7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn7KeyPressed(evt);
            }
        });
        jPanel1.add(btn7);

        btn8.setText("8");
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });
        btn8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn8KeyPressed(evt);
            }
        });
        jPanel1.add(btn8);

        btn9.setText("9");
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });
        btn9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn9KeyPressed(evt);
            }
        });
        jPanel1.add(btn9);

        btnMinus.setText("-");
        btnMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinusMouseClicked(evt);
            }
        });
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        btnMinus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMinusKeyPressed(evt);
            }
        });
        jPanel1.add(btnMinus);

        btnPatial.setText("1/x");
        btnPatial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPatialMouseClicked(evt);
            }
        });
        btnPatial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatialActionPerformed(evt);
            }
        });
        btnPatial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPatialKeyPressed(evt);
            }
        });
        jPanel1.add(btnPatial);

        btn0.setText("0");
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn0MouseClicked(evt);
            }
        });
        btn0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn0KeyPressed(evt);
            }
        });
        jPanel1.add(btn0);

        btnChange.setText("+/-");
        btnChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeMouseClicked(evt);
            }
        });
        btnChange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnChangeKeyPressed(evt);
            }
        });
        jPanel1.add(btnChange);

        btnClear.setText("C");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        btnClear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnClearKeyPressed(evt);
            }
        });
        jPanel1.add(btnClear);

        btnAdd.setText("+");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKeyPressed(evt);
            }
        });
        jPanel1.add(btnAdd);

        btnEqual.setText("=");
        btnEqual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEqualMouseClicked(evt);
            }
        });
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        btnEqual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEqualKeyPressed(evt);
            }
        });
        jPanel1.add(btnEqual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnChangeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnChangeKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnChangeKeyPressed

    private void showSuccess(String message) {
        JOptionPane.showMessageDialog(this, message, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Thông báo", JOptionPane.ERROR_MESSAGE);
    }

    private void btnClearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnClearKeyPressed
        // TODO add your handling code here:
        this.txtResult.setText("");
    }//GEN-LAST:event_btnClearKeyPressed
    public void showNumber(javax.swing.JButton btn) {
        String value = txtResult.getText();
        if (value.length() < 12) {
            if (value.equals("0") || check) {
                check = false;
                value = "";
            }
            this.txtResult.setText(value + btn.getText());
        } else {
            showError("Máy tính chỉ tính được độ dài không quá 12 vui lòng hoàn thành xong quá trình tính toàn hoặc clear ô tính");
        }
    }
    private void btn1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn1KeyPressed

    private void btn2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2KeyPressed

    private void btn3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3KeyPressed

    private void btn4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4KeyPressed

    private void btn5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5KeyPressed

    private void btn6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6KeyPressed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7KeyPressed

    private void btn8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8KeyPressed

    private void btn9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn9KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9KeyPressed

    private void btn0KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn0KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn0KeyPressed

    private void btnDivideKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDivideKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDivideKeyPressed

    private void btnMultipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMultipKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultipKeyPressed

    public void setResult(String operator) {
        try {
            Long.valueOf(this.txtResult.getText());
            if (!this.operator.isEmpty() && result != 0) {
                switch (this.operator) {
                    case "+":
                        this.result += Double.parseDouble(this.txtResult.getText());
                        break;
                    case "-":
                        this.result -= Double.parseDouble(this.txtResult.getText());
                        break;
                    case "*":
                        this.result *= Double.parseDouble(this.txtResult.getText());
                        break;
                    case "/": {
                        if (Double.parseDouble(this.txtResult.getText()) == 0) {
                            this.showError("Không thể chia một số cho 0");
                            result = 0;
                            operator = "";
                            check = false;
                            return;
                        }
                        this.result /= Double.parseDouble(this.txtResult.getText());
                    }
                    break;
                    case "%": {
                        if (Double.parseDouble(this.txtResult.getText()) == 0) {
                            this.showError("Không thể chia một số cho 0");
                            result = 0;
                            operator = "";
                            check = false;
                            return;
                        }
                        this.result %= Double.parseDouble(this.txtResult.getText());
                        break;
                    }
                }
            } else {
                result = Double.parseDouble(this.txtResult.getText());
            }
            if (result != 0 || this.checkZero) {
                this.operator = operator;
                this.txtResult.setText(operator);
                check = true;
            }
        } catch (NumberFormatException ex) {

            this.operator = operator;
            this.txtResult.setText(operator);
            check = true;

        }
    }
    private void btnMinusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMinusKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinusKeyPressed

    private void btnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAddKeyPressed

    private void btnChiaLayDuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnChiaLayDuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChiaLayDuKeyPressed

    private void btnEqualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEqualKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnEqualKeyPressed

    private void btnSqrtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSqrtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSqrtKeyPressed

    private void btnPatialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPatialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPatialKeyPressed

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        // TODO add your handling code here:
        this.showNumber(btn1);
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        // TODO add your handling code here:
        this.showNumber(btn2);
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        // TODO add your handling code here:
        this.showNumber(btn3);
    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        // TODO add your handling code here:
        this.showNumber(btn4);
    }//GEN-LAST:event_btn4MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        // TODO add your handling code here:
        this.showNumber(btn5);
    }//GEN-LAST:event_btn5MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        // TODO add your handling code here:
        this.showNumber(btn6);
    }//GEN-LAST:event_btn6MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        // TODO add your handling code here:
        this.showNumber(btn7);
    }//GEN-LAST:event_btn7MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        // TODO add your handling code here:
        this.showNumber(btn8);
    }//GEN-LAST:event_btn8MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        // TODO add your handling code here:
        this.showNumber(btn9);
    }//GEN-LAST:event_btn9MouseClicked

    private void btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseClicked
        // TODO add your handling code here:
        this.checkZero = true;
        this.showNumber(btn0);
    }//GEN-LAST:event_btn0MouseClicked

    private void btnChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeMouseClicked
        // TODO add your handling code here:
        if (this.txtResult.getText().equals("0")) {
            return;
        }
        if (String.valueOf(txtResult.getText().toCharArray()[0]).equalsIgnoreCase("-")) {
            txtResult.setText(txtResult.getText().substring(1));
        } else {
            txtResult.setText("-" + txtResult.getText());
        }
        if(this.result == 0 && this.operator.isEmpty()){
           this.result = Double.parseDouble(this.txtResult.getText());
        }
    }//GEN-LAST:event_btnChangeMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        this.txtResult.setText("0");
        this.checkZero = false;
        this.result = 0;
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:

        this.setResult("+");
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseClicked
        // TODO add your handling code here:
        this.setResult("-");
    }//GEN-LAST:event_btnMinusMouseClicked

    private void btnMultipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultipMouseClicked
        // TODO add your handling code here:
        this.setResult("*");
    }//GEN-LAST:event_btnMultipMouseClicked

    private void btnDivideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivideMouseClicked
        // TODO add your handling code here:
        this.setResult("/");
    }//GEN-LAST:event_btnDivideMouseClicked

    private void btnSqrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqrtMouseClicked
        // TODO add your handling code here:
        try {
            Double.valueOf(this.txtResult.getText());
            this.result = Math.sqrt(Double.parseDouble(this.txtResult.getText()));
            this.txtResult.setText(String.valueOf(result));
            checkResult();
        } catch (NumberFormatException ex) {
            if (this.result == 0) {
                this.showError("Vui lòng nhập vào một số trước khi dùng sqrt");
            } else {
                this.txtResult.setText(String.valueOf(Math.sqrt(result)));
            }
        }
    }//GEN-LAST:event_btnSqrtMouseClicked

    private void btnChiaLayDuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChiaLayDuMouseClicked
        // TODO add your handling code here:
        this.setResult("%");
    }//GEN-LAST:event_btnChiaLayDuMouseClicked

    private void btnPatialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatialMouseClicked
        // TODO add your handling code here:
        if (this.txtResult.getText().equals("0")) {
            showError("Không thể chia 1 số cho 0");
            return;
        }
        try {
            Double.valueOf(this.txtResult.getText());
            this.result = 1 / Double.parseDouble(this.txtResult.getText());
            this.txtResult.setText(String.valueOf(result));
            checkResult();
        } catch (NumberFormatException ex) {
            if (this.result == 0) {
                this.showError("Vui lòng nhập vào một số trước khi dùng 1/x");
            } else {
                this.txtResult.setText(String.valueOf(1 / result));
            }
        }

    }//GEN-LAST:event_btnPatialMouseClicked

    private void btnEqualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqualMouseClicked
        // TODO add your handling code here:
        this.showResult(this.operator);
    }//GEN-LAST:event_btnEqualMouseClicked

    private void showResult(String operator) {
        if (operator.isEmpty()) {
            return;
        }
        try {
            Double.valueOf(this.txtResult.getText());
            switch (operator) {
                case "+":
                    this.txtResult.setText(String.valueOf(this.result + Double.parseDouble(this.txtResult.getText())));
                    break;
                case "-":
                    this.txtResult.setText(String.valueOf(this.result - Double.parseDouble(this.txtResult.getText())));
                    break;
                case "*": {
                    this.txtResult.setText(String.valueOf(this.result * Double.parseDouble(this.txtResult.getText())));
                }
                break;
                case "/": {
                    if (Double.parseDouble(this.txtResult.getText()) == 0) {
                        this.showError("Không thể chia một số cho 0");
                        result = 0;
                        operator = "";
                        check = false;
                        return;
                    }
                    this.txtResult.setText(String.valueOf(this.result / Double.parseDouble(this.txtResult.getText())));
                    break;
                }

                case "%": {
                    if (Double.parseDouble(this.txtResult.getText()) == 0) {
                        this.showError("Không thể chia một số cho 0");
                        result = 0;
                        operator = "";
                        check = false;
                        return;
                    }
                    this.txtResult.setText(String.valueOf(this.result % Double.parseDouble(this.txtResult.getText())));
                    break;
                }

            }
            this.operator = "";
            checkResult();
            result = Double.parseDouble(this.txtResult.getText());
        } catch (NumberFormatException ex) {
            this.showError(ex.getMessage());
        }
    }

    private void checkResult() {
        if (this.txtResult.getText().equals("-0.0")) {
            this.txtResult.setText("0");
            return;
        }
        if (isInteger(this.txtResult.getText())) {
            String temp = String.valueOf(convertInteger(this.txtResult.getText()));
            if (Double.parseDouble(temp) == Double.parseDouble(temp)) {
                this.txtResult.setText(String.valueOf(convertInteger(this.txtResult.getText())));
            }
        } else {
            this.txtResult.setText(this.txtResult.getText());
        }
    }

    public static boolean isInteger(String s) {
        if (s.isEmpty()) {
            return false;
        }
        boolean check = false;
        boolean checkk = false;
        for (int i = 0; i < s.length(); i++) {
            if (i == 0 && s.charAt(i) == '-') {
                continue;
            }
            if (check) {
                if (!String.valueOf(s.charAt(i)).equals("0")) {
                    checkk = true;
                }
            }
            if (String.valueOf(s.charAt(i)).equals(".")) {
                check = true;
                continue;
            }
            if (!Character.isDigit(s.charAt(i))) {
                return false;
            }
        }
        if (checkk) {
            return false;
        } else {
            return true;
        }
    }

    private String convertInteger(String a) {
        String[] parts = a.toString().split("\\.");
        return parts[0];
    }
    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnPatialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPatialActionPerformed

    private void btnMultipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultipActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMultipActionPerformed

    private void btnChiaLayDuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaLayDuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChiaLayDuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnChiaLayDu;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultip;
    private javax.swing.JButton btnPatial;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
